server:
  port: 8065

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.prs.services

spring:
  r2dbc:
    url: r2dbc:h2:file://./../etc/${spring.application.name}-h2-db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${username}
    password: ${password}

info:
  app:
    name: ${spring.application.name}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    environment: ${spring.profiles.active}
    java:
      version: ${java.version}