server:
  port: 8088
spring:
  application:
    name: config-service
  profiles:   
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasath116/cloud-config
          try-master-branch: true
#          clone-on-start: true
#          default-label: main
          search-paths: cloud-reactive-configs
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061/eureka/
          
